"""Canonical DuckDB schema shared by live ingest and retained corpora."""

from __future__ import annotations

ANALYTICS_TABLES = (
    "executions",
    "operations",
    "links",
    "events",
    "evaluations",
    "outcomes",
    "expected_derived_insights",
)

ANALYTICS_COLUMNS: dict[str, tuple[str, ...]] = {
    "executions": ("execution_id", "runtime_id", "started_at", "ended_at", "status", "schema_version", "attributes"),
    "operations": (
        "operation_id",
        "execution_id",
        "trace_id",
        "span_id",
        "parent_span_id",
        "kind",
        "name",
        "status",
        "started_at",
        "ended_at",
        "attempt",
        "attributes",
    ),
    "links": ("link_id", "execution_id", "source_id", "target_id", "relation", "attributes"),
    "events": (
        "event_id",
        "execution_id",
        "trace_id",
        "span_id",
        "timestamp",
        "type",
        "name",
        "payload",
        "schema_version",
    ),
    "evaluations": (
        "evaluation_id",
        "execution_id",
        "subject_id",
        "name",
        "value",
        "label",
        "score",
        "source",
        "confidence",
        "definition_version",
        "attributes",
    ),
    "outcomes": ("outcome_id", "execution_id", "name", "status", "value", "timestamp", "attributes"),
    "expected_derived_insights": (
        "execution_id",
        "expected_template",
        "expected_repeated_pattern_count",
        "expected_repair_count",
        "expected_terminal_family",
        "expected_failure_operation",
        "expected_failure_key",
        "expected_path_signature",
        "expected_loop_signatures",
        "expected_tool_names",
        "expected_stage_keys",
        "expected_provider_roles",
        "expected_domain_enriched",
        "expected_recovered",
        "expected_model_calls",
        "expected_tool_calls",
        "expected_known_model_cost",
        "expected_cost_complete",
    ),
}

AGGREGATE_COLUMNS = (
    "entity_type",
    "canonical_key",
    "display_label",
    "executions",
    "calls",
    "failures",
    "iterations",
    "metric_value",
    "metric_text",
)
V2_ANALYTICS_TABLES = ANALYTICS_TABLES + ("expected_aggregate_insights",)
ANALYTICS_COLUMN_TYPES = {
    "attempt": "BIGINT",
    "score": "DOUBLE",
    "confidence": "DOUBLE",
    "expected_repeated_pattern_count": "BIGINT",
    "expected_repair_count": "BIGINT",
    "expected_domain_enriched": "BOOLEAN",
    "expected_recovered": "BOOLEAN",
    "expected_model_calls": "BIGINT",
    "expected_tool_calls": "BIGINT",
    "expected_known_model_cost": "DOUBLE",
    "expected_cost_complete": "BOOLEAN",
    "executions": "BIGINT",
    "calls": "BIGINT",
    "failures": "BIGINT",
    "iterations": "BIGINT",
    "metric_value": "DOUBLE",
}
